### ISSUE TITLE
EHP Project Goals and Milestones

### ISSUE THREAD

**Issue by teresathompson** [teresathompson/EHP#1]
# Background
Continuous Machine Learning is enabled by good workflow. Embedded in the workflow are the scripts that can be sourced from almost everywhere on the internet. 

Once the workflow has been setup, we can solicit better python scripts similar to kaggle. 

# Goals
- [ ] Using public datasets and a public repository, code a multi-model workflow using DVC, CML and GitHub Actions
  - [ ] Integration should include GCP as a DVC Remote
     - This is basically the tutorials
- [ ] TensorFlow Cloud w/GPU called via python script from GitHub runner
  - Test DVC to interact with files and repo during this part
  - This is one of the most elegant parts of this solution 
  
# Pipeline Milestones
- [ ] Get the same dataset and model dynamically driving workflow in separate folders using separate dvc.yaml files
  - [ ] Test: Modify one dataset
  - [ ] Test: Modify both datasets 
  - [ ] Test: Modify input parameters 
- [ ] Ensure that GitHub Actions scripts are running
  - [ ] Test: Reproduce models only for modified datasets
- [ ] Apply to obfuscated EHP datasets 

# Pipeline Capabilities
- [ ] Quickly introduce new workflow for new models
- [ ] Well integrated metrics and loss for the basic classifier and regression models 
- [ ] Refined visual feedback
  - [ ] Visuals go in both Model ReadMe's and Pull Requests used to train models 

# What data do we work with
- [ ] All of the sample datasets mentioned in this article: https://explained.ai/decision-tree-viz/index.html
  - We can get good with the simple stuff and then include calls to TensorFlow Cloud to train models with GPU available
- [ ] Use EHP Datasets in Pipeline
  - [ ] 3000 column, 1million record datasets for feature reduction e.g. featurewiz 
    - [ ] Sample records for feature reduction rather than use all 1 million 
    - [ ]   
  - [ ] 95 Column, 215 K records dataset for model training
